name       : python-colour
version    : 0.1.5
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/c/colour/colour-0.1.5.tar.gz : af20120fefd2afede8b001fbef2ea9da70ad7d49fafdb6489025dae8745c3aee
license    : BSD-2-Clause
component  : programming.python
summary    : Colour representations manipulation library (RGB, HSL, web, ...)
description: |
    Colour representations manipulation library (RGB, HSL, web, ...)
builddeps  :
    - python-d2to1
    - python-nose
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
