name       : python-colour
version    : 0.1.4
release    : 2
source     :
    - https://pypi.python.org/packages/c3/b3/343cd523aabf275f54638a40434392699a2e29acef1044c442228b3aac13/colour-0.1.4.tar.gz : 1357f37ddfd0d7c0e770f0772901635b3a38025a2480a44280510faca30fb509
license    : BSD-2-Clause
component  : programming.python
summary    : Colour representations manipulation library (RGB, HSL, web, ...)
description: |
    Colour representations manipulation library (RGB, HSL, web, ...)
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-d2to1
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
